projects:
  app:
    schemaPath: "src/schema.graphql"
    includes: ["queries/{booking,queries}.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:5000"
  database:
    schemaPath: "database/schema.generated.graphql"
    includes: ["database/seed.graphql"]
    extensions:
      graphcool: graphcool.yml
