projects:
  database:
    schemaPath: "schemas/db-service.graphql"
    includes: ["queries/seed.graphql", "src/schema.graphql"]
    extensions:
      endpoints:
        default:
          url: "https://api.graph.cool/simple/v1/${env:GRAPHCOOL_SERVICE_ID}"
          subscription: "wss://subscriptions.graph.cool/v1/${env:GRAPHCOOL_SERVICE_ID}"
  gateway:
    schemaPath: "schemas/gateway.graphql"
    includes: ["queries/{booking,queries}.graphql"]
    extensions:
      endpoints:
        dev:
          url: "http://localhost:4000"
          subscription: "ws://localhost:4000"