projects:
  app:
    schemaPath: "src/schema.graphql"
    includes: ["queries/{booking,queries}.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:5000"
      bundle: src/generated/app.graphql
  database:
    schemaPath: "database/schema.generated.graphql"
    includes: ["database/seed.graphql"]
    extensions:
      graphcool: graphcool.yml
      binding:
        output: src/generated/graphcool.ts
        generator: graphcool-ts
