projects:
  app:
    schemaPath: "src/schemas/app.graphql"
    includes: ["queries/{booking,queries}.graphql"]
    extensions:
      endpoints:
        default: "${env:SERVER_ENDPOINT}"
  database:
    schemaPath: "src/schemas/database.graphql"
    includes: ["database/seed.graphql"]
    extensions:
      endpoints:
        default:
          url: "${env:GRAPHCOOL_ENDPOINT}"
          headers:
            Authorization: "Bearer ${env:GRAPHCOOL_APIKEY}"
